CREATE TABLE IF NOT EXISTS users (
   username VARCHAR(50) PRIMARY KEY,
   pswd VARCHAR(50) NOT NULL,
   authority VARCHAR(10) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS members (
   id SMALLINT(3) ZEROFILL UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   membername VARCHAR(50) NOT NULL,
   phone VARCHAR(20) NOT NULL
) ENGINE=INNODB;

CREATE TABLE books (
   id SMALLINT(3) ZEROFILL UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(50) NOT NULL,
   author VARCHAR(50),
   available VARCHAR(5) NOT NULL
) ENGINE=INNODB;

CREATE TABLE rentals (
   id SMALLINT(3) ZEROFILL UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   memberid SMALLINT(3) ZEROFILL UNSIGNED NOT NULL,
   bookid SMALLINT(3) ZEROFILL UNSIGNED NOT NULL,
   rentdate DATE NOT NULL,
   duedate DATE NOT NULL,
   returndate DATE,
   penaltyfee DOUBLE(5, 2),
   rentstatus VARCHAR(10) NOT NULL,
      INDEX (memberid),
      INDEX (bookid),
         FOREIGN KEY (memberid) REFERENCES members(id) ON UPDATE CASCADE ON DELETE CASCADE,
         FOREIGN KEY (bookid) REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;